version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: repick-community
      MYSQL_USER: dev
      MYSQL_PASSWORD: 1234
    ports:
      - "3309:3306"
  redis:
    image: redis:latest
    container_name: community-redis
    ports:
      - "6381:6379"